version: "3.7"

services:
  grafana:
    image: grafana/grafana
    restart: on-failure
    user: "$UID:$GID"
    ports:
    - 3000:3000
    volumes:
    - ./grafana_data:/var/lib/grafana
    restart: always

  influxdb:
    #image: quay.io/influxdb/influxdb:v2.0.4
    image: influxdb:latest
    #container_name: influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: db0
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: 1234
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb
